### ISSUE TITLE
Unable to build in Windows since 2.0.1

### ISSUE THREAD

**Issue by d-divita** [antony-jr/QArchive#44]
**Select your issue type:** (check at least one)
- [x] Bug
- [ ] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
I'm trying to build a project with your library; since version 2.0.1, I'm no more able to correctly build (I've figured out a workaround for version 2.0.2, but it doesn't work for 2.1.0).
I [directly added QArchive to my project](https://antonyjr.in/QArchive/docs/AddingQArchive.html#directly-adding-qarchive-to-your-project), then I created a "libarchive" folder within the QArchive one with the libarchive .dll and .h. I modified the QArchive.pri file to look into that folder `(INCLUDEPATH += $$PWD $$PWD/include $$PWD/other/qmake $$PWD/libarchive
LIBS += -L$$PWD/libarchive/ -larchive)`, but when I build the project there are 200+ errors like this: `qarchivememoryextractoroutput.cc: error: undefined reference to `__imp__ZN8QArchive10MemoryFileD1Ev'`

The same happens when I try to build the examples. With version 2.0.0, there are no errors.

My setup: Qt 5.15.2 on Windows 10, MinGW 8.1 64bit.

Thank you

**Comment by antony-jr** [comment]
I will look into it. But you can also use it from conan https://conan.io/center/qarchive

**Comment by d-divita** [comment]
Honestly I have no idea of how to use it, I looked at your documentation but it is still obscure to me, and in addition I'm using qmake so I don't want to switch to cmake

**Comment by antony-jr** [comment]
@d-divita I have deployed a fix to the master branch please test it out. Make sure to use the new pri file https://github.com/antony-jr/QArchive/blob/master/QArchive.pri

The issue was that I forgot to define ```QARCHIVE_STATIC``` in the pri file. This was in the .pro file so the library compiled but not other projects which only included the pri file. So now I've moved the definition to pri file.

**I tested this in Windows 10 (Virtual Machine), MinGW 7.2 64 bit (Qt 5.12)**

# Example

## YourApplication.pro

```
include(QArchive/QArchive.pri)
LIBS += -L $$PWD/libarchive
INCLUDEPATH += $$PWD/libarchive

# All other project configs
# if you use CONFIG += shared
# then you should uncomment the following line
# DEFINES -= QARCHIVE_STATIC 
```

**Comment by d-divita** [comment]
Thanks a lot, now it works flawlessly!
