### ISSUE TITLE
QArchive does not build with QT 6.2.4

### ISSUE THREAD

**Issue by lmussier** [antony-jr/QArchive#58]
**Select your issue type:** (check at least one)
- [ ] Bug
- [ ] Question
- [ ] Suggestion
- [x] Other (please describe):

**Describe your issue:**

Building QArchive fails on ubuntu 22.04 + QT 6.2.4.

**Ways to Reproduce the issue (optional):**

1. Grab a 22.04.
2. Install QT 6.2.4
3. git clone https://github.com/antony-jr/QArchive.git @ v2.2.0
4. cmake / make
5. You'll get this error (among others)

```
/home/lmussier/workspace/QArchive/src/qarchivecompressor_p.cc: In member function ‘short int QArchive::CompressorPrivate::compress()’:
/home/lmussier/workspace/QArchive/src/qarchivecompressor_p.cc:819:80: error: ‘class QDateTime’ has no member named ‘toTime_t’
  819 |             archive_entry_set_atime(entry.data(), static_cast<time_t>(datetime.toTime_t()), 0);
      |                                                                                ^~~~~~~~
/home/lmussier/workspace/QArchive/src/qarchivecompressor_p.cc:820:80: error: ‘class QDateTime’ has no member named ‘toTime_t’
  820 |             archive_entry_set_mtime(entry.data(), static_cast<time_t>(datetime.toTime_t()), 0);
      |                                                                                ^~~~~~~~
/home/lmussier/workspace/QArchive/src/qarchivecompressor_p.cc:821:84: error: ‘class QDateTime’ has no member named ‘toTime_t’
  821 |             archive_entry_set_birthtime(entry.data(), static_cast<time_t>(datetime.toTime_t()), 0);
      |      
                                                                              ^~~~~~~~
```

You'll also see deprecation warnings for this https://doc-snapshots.qt.io/qt6-dev/qscopedpointer-obsolete.html, bu tit does not prevent the compilation yet.

**Comment by lmussier** [comment]
Hmm since that the fix is straightforward regarding #45

**Comment by antony-jr** [comment]
QArchive is still not tested with Qt6, I think its time we add that to avoid cases like this in the future.. Seems like an easy fix. Will do asap. (or you can send a PR if you like)

**Comment by lmussier** [comment]
@antony-jr done with #59

**Comment by lmussier** [comment]
Thanks for the work and the reactivity 👍
